[build]
  publish = "public"
  functions = "netlify/functions"
  command = "./build.sh"
  ignore = "git diff --quiet HEAD^ HEAD -- netlify/ package.json netlify.toml"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# 设置环境变量
[build.environment]
  NODE_VERSION = "18"
  # 明确停用Python
  PYTHON_VERSION = "false"
  # 使用Node而不是Python
  USE_NODE_RUNTIME = "true"
  # 不使用yarn
  NETLIFY_USE_YARN = "false"

# 配置缓存控制
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60"
