[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# 设置环境变量（生产环境中应通过Netlify控制台设置）
[build.environment]
  NODE_VERSION = "18"

# 配置缓存控制
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60" 